// packages/svelte/src/lib/components/tooltip/tooltip-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Tooltip as TooltipPrimitive } from "bits-ui";
import { getTooltipContext } from "./tooltip.context.js";

let {
	ref = $bindable(null),
	class: className,
	sideOffset = 4,
	...rest
}: TooltipPrimitive.ContentProps = $props();

const context = getTooltipContext();
</script>

<TooltipPrimitive.Portal>
	<TooltipPrimitive.Content
		bind:ref
		{sideOffset}
		class={cn(context.slots.content(), className)}
		{...rest}
	>
		{@render rest.children?.()}
	</TooltipPrimitive.Content>
</TooltipPrimitive.Portal>

// packages/react/src/components/tooltip/tooltip-content.tsx
import { cn } from "@adn-ui/core";
import { Tooltip } from "radix-ui";

import { useTooltipContext } from "./tooltip-context";

export type TooltipContentProps = React.ComponentProps<typeof Tooltip.Content>;

export default function TooltipContent({
  children,
  className,
  side = "top",
  sideOffset = 4,
  ...props
}: TooltipContentProps) {
  const { slots } = useTooltipContext();

  return (
    <Tooltip.Portal>
      <Tooltip.Content
        data-slot="tooltip-content"
        side={side}
        sideOffset={sideOffset}
        className={cn(slots.content(), className)}
        {...props}
      >
        {children}
      </Tooltip.Content>
    </Tooltip.Portal>
  );
}
