// packages/svelte/src/lib/components/tooltip/tooltip-root.svelte
<script lang="ts">
import { tooltipVariants } from "@adn-ui/core";
import { Tooltip as TooltipPrimitive } from "bits-ui";
import { setTooltipContext } from "./tooltip.context.js";

let { open = $bindable(false), ...rest }: TooltipPrimitive.RootProps = $props();

const slots = tooltipVariants();
setTooltipContext({
	get slots() {
		return slots;
	},
});
</script>

<TooltipPrimitive.Root bind:open {...rest}>
	{@render rest.children?.()}
</TooltipPrimitive.Root>

// packages/react/src/components/tooltip/tooltip-root.tsx
import { tooltipVariants } from "@adn-ui/core";
import { Tooltip } from "radix-ui";

import { TooltipContext } from "./tooltip-context";

export type TooltipRootProps = React.ComponentProps<typeof Tooltip.Root>;

export default function TooltipRoot(props: TooltipRootProps) {
	const slots = tooltipVariants();

	return (
		<TooltipContext value={{ slots }}>
			<Tooltip.Root data-slot="tooltip-root" {...props} />
		</TooltipContext>
	);
}
