// packages/svelte/src/lib/components/tooltip/tooltip-arrow.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Tooltip as TooltipPrimitive } from "bits-ui";
import { getTooltipContext } from "./tooltip.context.js";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: TooltipPrimitive.ArrowProps = $props();

const context = getTooltipContext();
</script>

<TooltipPrimitive.Arrow
	bind:ref
	class={cn(context.slots.arrow(), className)}
	{...rest}
/>

// packages/react/src/components/tooltip/tooltip-arrow.tsx
import { cn } from "@adn-ui/core";
import { Tooltip } from "radix-ui";

import { useTooltipContext } from "./tooltip-context";

export type TooltipArrowProps = React.ComponentProps<typeof Tooltip.Arrow>;

export default function TooltipArrow({ className, ...props }: TooltipArrowProps) {
  const { slots } = useTooltipContext();

  return (
    <Tooltip.Arrow data-slot="tooltip-arrow" className={cn(slots.arrow(), className)} {...props} />
  );
}
