// packages/svelte/src/lib/components/alert-dialog/alert-dialog-description.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.DescriptionProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Description
	bind:ref
	class={cn(slots.description(), className)}
	{...rest}
/>

// src/components/ui/alert-dialog/alert-dialog-description.tsx
import { AlertDialog } from "radix-ui";
import { cn } from "tailwind-variants";

import { useAlertDialogContext } from "./alert-dialog.context";

export type AlertDialogDescriptionProps = React.ComponentProps<typeof AlertDialog.Description>;

export const AlertDialogDescription = ({ className, ...props }: AlertDialogDescriptionProps) => {
  const { slots } = useAlertDialogContext();

  return <AlertDialog.Description className={cn(slots.description(), className)} {...props} />;
};
