// packages/svelte/src/lib/components/accordion/accordion-trigger.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Accordion as AccordionPrimitive } from "bits-ui";
import { LucideChevronDown } from "lucide-svelte";
import { getAccordionContext } from "./accordion.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AccordionPrimitive.TriggerProps = $props();

const { slots } = getAccordionContext();
</script>

<AccordionPrimitive.Trigger
	bind:ref
	class={cn(slots.trigger(), className)}
	{...rest}
>
	{@render rest.children?.()}
	<LucideChevronDown class={slots.chevron()} aria-hidden="true" />
</AccordionPrimitive.Trigger>

// packages/react/src/components/accordion/accordion-trigger.tsx
import { cn } from "@adn-ui/core";
import { ChevronDown } from "lucide-react";
import { Accordion } from "radix-ui";

import { useAccordionContext } from "./accordion-context";
import AccordionHeader from "./accordion-header";

export type AccordionTriggerProps = React.ComponentProps<typeof Accordion.Trigger>;

export default function AccordionTrigger({ children, className, ...props }: AccordionTriggerProps) {
  const { slots } = useAccordionContext();

  return (
    <AccordionHeader>
      <Accordion.Trigger
        data-slot="accordion-trigger"
        className={cn(slots.trigger(), className)}
        {...props}
      >
        {children}
        <ChevronDown className={slots.chevron()} aria-hidden />
      </Accordion.Trigger>
    </AccordionHeader>
  );
}
