// packages/svelte/src/lib/components/accordion/accordion-item.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Accordion as AccordionPrimitive } from "bits-ui";
import { getAccordionContext } from "./accordion.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AccordionPrimitive.ItemProps = $props();

const { slots } = getAccordionContext();
</script>

<AccordionPrimitive.Item
	bind:ref
	class={cn(slots.item(), className)}
	{...rest}
>
	{@render rest.children?.()}
</AccordionPrimitive.Item>

// packages/react/src/components/accordion/accordion-item.tsx
import { cn } from "@adn-ui/core";
import { Accordion } from "radix-ui";

import { useAccordionContext } from "./accordion-context";

export type AccordionItemProps = React.ComponentProps<typeof Accordion.Item>;

export default function AccordionItem({ className, ...props }: AccordionItemProps) {
  const { slots } = useAccordionContext();

  return (
    <Accordion.Item data-slot="accordion-item" className={cn(slots.item(), className)} {...props} />
  );
}
