// packages/svelte/src/lib/components/accordion/accordion-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Accordion as AccordionPrimitive } from "bits-ui";
import { getAccordionContext } from "./accordion.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AccordionPrimitive.ContentProps = $props();

const { slots } = getAccordionContext();
</script>

<AccordionPrimitive.Content
	bind:ref
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</AccordionPrimitive.Content>

// packages/react/src/components/accordion/accordion-content.tsx
import { cn } from "@adn-ui/core";
import { Accordion } from "radix-ui";

import { useAccordionContext } from "./accordion-context";

export type AccordionContentProps = React.ComponentProps<typeof Accordion.Content>;

export default function AccordionContent({ children, className, ...props }: AccordionContentProps) {
  const { slots } = useAccordionContext();

  return (
    <Accordion.Content
      data-slot="accordion-content"
      className={cn(slots.content(), className)}
      {...props}
    >
      {children}
    </Accordion.Content>
  );
}
