// packages/react/src/components/context-menu/context-menu-root.tsx
import { contextMenuVariants } from "@adn-ui/core";
import { ContextMenu } from "radix-ui";

import { ContextMenuContext } from "./context-menu-context";

export type ContextMenuRootProps = React.ComponentProps<typeof ContextMenu.Root>;

export default function ContextMenuRoot(props: ContextMenuRootProps) {
  const slots = contextMenuVariants();

  return (
    <ContextMenuContext value={{ slots }}>
      <ContextMenu.Root data-slot="context-menu-root" {...props} />
    </ContextMenuContext>
  );
}

// packages/svelte/src/lib/components/context-menu/context-menu-root.svelte
<script lang="ts">
import { contextMenuVariants } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { setContextMenuContext } from "./context-menu.context";

let { children, ...rest }: ContextMenuPrimitive.RootProps = $props();

const slots = contextMenuVariants();
setContextMenuContext({
	get slots() {
		return slots;
	},
});
</script>

<ContextMenuPrimitive.Root {...rest}>
	{@render children?.()}
</ContextMenuPrimitive.Root>
