// packages/react/src/components/context-menu/context-menu-content.tsx
import { cn } from "@adn-ui/core";
import { ContextMenu } from "radix-ui";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuContentProps = React.ComponentProps<typeof ContextMenu.Content>;

export default function ContextMenuContent({
  children,
  className,
  ...props
}: ContextMenuContentProps) {
  const { slots } = useContextMenuContext();

  return (
    <ContextMenu.Portal>
      <ContextMenu.Content
        data-slot="context-menu-content"
        className={cn(slots.content(), className)}
        {...props}
      >
        {children}
      </ContextMenu.Content>
    </ContextMenu.Portal>
  );
}

// packages/svelte/src/lib/components/context-menu/context-menu-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { getContextMenuContext } from "./context-menu.context";

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: ContextMenuPrimitive.ContentProps = $props();

const context = getContextMenuContext();
</script>

<ContextMenuPrimitive.Content
	bind:ref
	class={cn(context.slots.content(), className)}
	{...rest}
>
	{@render children?.()}
</ContextMenuPrimitive.Content>
