// packages/react/src/components/context-menu/context-menu-sub-content.tsx
import { cn } from "@adn-ui/core";
import { ContextMenu } from "radix-ui";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuSubContentProps = React.ComponentProps<typeof ContextMenu.SubContent>;

export default function ContextMenuSubContent({ className, ...props }: ContextMenuSubContentProps) {
  const { slots } = useContextMenuContext();

  return (
    <ContextMenu.Portal>
      <ContextMenu.SubContent
        data-slot="context-menu-sub-content"
        className={cn(slots.subContent(), className)}
        {...props}
      />
    </ContextMenu.Portal>
  );
}

// packages/svelte/src/lib/components/context-menu/context-menu-sub-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { getContextMenuContext } from "./context-menu.context";

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: ContextMenuPrimitive.SubContentProps = $props();

const context = getContextMenuContext();
</script>

<ContextMenuPrimitive.SubContent
	bind:ref
	class={cn(context.slots.subContent(), className)}
	{...rest}
>
	{@render children?.()}
</ContextMenuPrimitive.SubContent>
