// packages/svelte/src/lib/components/scroll-area/scroll-area-scrollbar.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ScrollArea as ScrollAreaPrimitive } from "bits-ui";
import { getScrollAreaContext } from "./scroll-area.context.js";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: ScrollAreaPrimitive.ScrollbarProps = $props();

const slots = getScrollAreaContext();
</script>

<ScrollAreaPrimitive.Scrollbar
	bind:ref
	class={cn(slots.scrollbar(), className)}
	{...rest}
>
	{@render rest.children?.()}
</ScrollAreaPrimitive.Scrollbar>

// packages/react/src/components/scroll-area/scroll-area-scrollbar.tsx
import { cn } from "@adn-ui/core";
import { ScrollArea } from "radix-ui";

import { useScrollAreaContext } from "./scroll-area-context";

export type ScrollAreaScrollbarProps = React.ComponentProps<typeof ScrollArea.Scrollbar>;

export default function ScrollAreaScrollbar({
  className,
  orientation = "vertical",
  ...props
}: ScrollAreaScrollbarProps) {
  const { slots } = useScrollAreaContext();

  return (
    <ScrollArea.Scrollbar
      data-slot="scroll-area-scrollbar"
      orientation={orientation}
      className={cn(slots.scrollbar(), className)}
      {...props}
    />
  );
}
