// packages/svelte/src/lib/components/scroll-area/scroll-area-thumb.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ScrollArea as ScrollAreaPrimitive } from "bits-ui";
import { getScrollAreaContext } from "./scroll-area.context.js";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: ScrollAreaPrimitive.ThumbProps = $props();

const slots = getScrollAreaContext();
</script>

<ScrollAreaPrimitive.Thumb
	bind:ref
	class={cn(slots.thumb(), className)}
	{...rest}
/>

// packages/react/src/components/scroll-area/scroll-area-thumb.tsx
import { cn } from "@adn-ui/core";
import { ScrollArea } from "radix-ui";

import { useScrollAreaContext } from "./scroll-area-context";

export type ScrollAreaThumbProps = React.ComponentProps<typeof ScrollArea.Thumb>;

export default function ScrollAreaThumb({ className, ...props }: ScrollAreaThumbProps) {
  const { slots } = useScrollAreaContext();

  return (
    <ScrollArea.Thumb
      data-slot="scroll-area-thumb"
      className={cn(slots.thumb(), className)}
      {...props}
    />
  );
}
