// packages/react/src/components/slider/slider-root.tsx
import { type SliderVariants, sliderVariants } from "@adn-ui/core";
import { Slider } from "radix-ui";

import { SliderContext } from "./slider-context";

export type SliderRootProps = React.ComponentProps<typeof Slider.Root> &
	SliderVariants;

export default function SliderRoot({
	className,
	size,
	...props
}: SliderRootProps) {
	const slots = sliderVariants({ size });

	return (
		<SliderContext value={{ slots }}>
			<Slider.Root
				data-slot="slider"
				className={slots.root({ className })}
				{...props}
			/>
		</SliderContext>
	);
}

// packages/svelte/src/lib/components/slider/slider-root.svelte
<script lang="ts">
import { cn, type SliderVariants, sliderVariants } from "@adn-ui/core";
import { Slider as SliderPrimitive } from "bits-ui";
import { setSliderContext } from "./slider.context.js";

type SliderRootProps = SliderPrimitive.RootProps & {
	type?: "single" | "multiple";
	size?: SliderVariants["size"];
};

let {
	ref = $bindable(null),
	value = $bindable(),
	type = "single",
	class: className,
	size = "md",
	...rest
}: SliderRootProps = $props();

const slots = $derived(sliderVariants({ size }));
setSliderContext({
	get slots() {
		return slots;
	},
});
</script>

	<SliderPrimitive.Root
		bind:ref
		bind:value
		type={type}
		class={cn(slots.root(), className)}
		{...rest  as any }
	/>
