// packages/svelte/src/lib/components/breadcrumb/breadcrumb-root.svelte
<script lang="ts">
import { breadcrumbVariants, cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { setBreadcrumbContext } from "./breadcrumb.context";

interface Props extends WithElementRef<HTMLAttributes<HTMLElement>> {}

let {
	ref = $bindable(null),
	children,
	class: className,
	...rest
}: Props = $props();

const slots = breadcrumbVariants();
setBreadcrumbContext({ slots });
</script>

<nav
	bind:this={ref}
	aria-label="breadcrumb"
	class={cn(slots.root(), className)}
	{...rest}
>
	{@render children?.()}
</nav>

// src/components/ui/breadcrumb/breadcrumb-root.tsx
import "./breadcrumb.css";
import { BreadcrumbContext } from "./breadcrumb.context";
import { breadcrumbVariants, type BreadcrumbVariants } from "./breadcrumb.variants";

export type BreadcrumbRootProps = BreadcrumbVariants & React.ComponentProps<"nav">;

export const BreadcrumbRoot = ({ children, ...props }: BreadcrumbRootProps) => {
  const slots = breadcrumbVariants();

  return (
    <BreadcrumbContext value={{ slots }}>
      <nav aria-label="breadcrumb" {...props}>
        {children}
      </nav>
    </BreadcrumbContext>
  );
};
