// packages/svelte/src/lib/components/alert/alert-root.svelte
<script lang="ts">
import { type AlertVariants, alertVariants, cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { setAlertContext } from "./alert.context";

interface Props
	extends WithElementRef<HTMLAttributes<HTMLDivElement>>,
		AlertVariants {}

let {
	ref = $bindable(null),
	class: className,
	variant = "default",
	...rest
}: Props = $props();

const slots = $derived(alertVariants({ variant }));
setAlertContext({
	get slots() {
		return slots;
	},
});
</script>

<div
	bind:this={ref}
	role="alert"
	class={cn(slots.root(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>

// src/components/ui/alert/alert-root.tsx
import "./alert.css";

import { cn } from "tailwind-variants";

import { AlertContext } from "./alert.context";
import { alertVariants, type AlertVariants } from "./alert.variants";

export type AlertRootProps = AlertVariants & React.ComponentProps<"div">;

export const AlertRoot = ({ children, className, variant, ...props }: AlertRootProps) => {
  const slots = alertVariants({ variant });

  return (
    <AlertContext value={{ slots }}>
      <div className={cn(slots.root(), className)} role="alert" {...props}>
        {children}
      </div>
    </AlertContext>
  );
};
