// packages/svelte/src/lib/components/select/select-root.svelte
<script lang="ts">
import { selectVariants } from "@adn-ui/core";
import { Select as SelectPrimitive } from "bits-ui";
import { setSelectContext } from "./select.context.js";

let { ...rest }: SelectPrimitive.RootProps = $props();

const slots = selectVariants();
setSelectContext({ slots });
</script>


<SelectPrimitive.Root	{...rest as any} />

// packages/react/src/components/select/select-root.tsx
import { selectVariants } from "@adn-ui/core";
import { Select } from "radix-ui";

import { SelectContext } from "./select-context";

export type SelectRootProps = React.ComponentProps<typeof Select.Root>;

export default function SelectRoot(props: SelectRootProps) {
	const slots = selectVariants();

	return (
		<SelectContext value={{ slots }}>
			<Select.Root data-slot="select-root" {...props} />
		</SelectContext>
	);
}
