// packages/svelte/src/lib/components/select/select-label.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Select as SelectPrimitive } from "bits-ui";
import { getSelectContext } from "./select.context.js";

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: SelectPrimitive.GroupHeadingProps = $props();

const context = getSelectContext();
</script>

<SelectPrimitive.GroupHeading
	bind:ref
	class={cn(context.slots.label(), className)}
	{...rest}
>
	{@render children?.()}
</SelectPrimitive.GroupHeading>

// packages/react/src/components/select/select-label.tsx
import { cn } from "@adn-ui/core";
import { Select } from "radix-ui";

import { useSelectContext } from "./select-context";

export type SelectLabelProps = React.ComponentProps<typeof Select.Label>;

export default function SelectLabel({ className, ...props }: SelectLabelProps) {
  const { slots } = useSelectContext();

  return (
    <Select.Label data-slot="select-label" className={cn(slots.label(), className)} {...props} />
  );
}
