// packages/svelte/src/lib/components/select/select-separator.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Select as SelectPrimitive } from "bits-ui";
import { getSelectContext } from "./select.context.js";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: SelectPrimitive.SeparatorProps = $props();

const context = getSelectContext();
</script>

<SelectPrimitive.Separator
	bind:ref
	class={cn(context.slots.separator(), className)}
	{...rest}
/>

// packages/react/src/components/select/select-separator.tsx
import { cn } from "@adn-ui/core";
import { Select } from "radix-ui";

import { useSelectContext } from "./select-context";

export type SelectSeparatorProps = React.ComponentProps<typeof Select.Separator>;

export default function SelectSeparator({ className, ...props }: SelectSeparatorProps) {
  const { slots } = useSelectContext();

  return (
    <Select.Separator
      data-slot="select-separator"
      className={cn(slots.separator(), className)}
      {...props}
    />
  );
}
