// packages/react/src/components/popover/popover-root.tsx
import { popoverVariants } from "@adn-ui/core";
import { Popover } from "radix-ui";

import { PopoverContext } from "./popover-context";

export type PopoverRootProps = React.ComponentProps<typeof Popover.Root>;

export default function PopoverRoot(props: PopoverRootProps) {
  const slots = popoverVariants();

  return (
    <PopoverContext value={{ slots }}>
      <Popover.Root data-slot="popover-root" {...props} />
    </PopoverContext>
  );
}

// packages/svelte/src/lib/components/popover/popover-root.svelte
<script lang="ts">
import { popoverVariants } from "@adn-ui/core";
import { Popover as PopoverPrimitive } from "bits-ui";
import { setPopoverContext } from "./popover.context";

let { open = $bindable(false), ...rest }: PopoverPrimitive.RootProps = $props();

const slots = popoverVariants();
setPopoverContext({ slots });
</script>

<PopoverPrimitive.Root bind:open {...rest}>
	{@render rest.children?.()}
</PopoverPrimitive.Root>
