// packages/react/src/components/popover/popover-close.tsx
import { cn } from "@adn-ui/core";
import { X } from "lucide-react";
import { Popover } from "radix-ui";

import { usePopoverContext } from "./popover-context";

export type PopoverCloseProps = React.ComponentProps<typeof Popover.Close>;

export default function PopoverClose({ children, className, ...props }: PopoverCloseProps) {
  const { slots } = usePopoverContext();

  return (
    <Popover.Close data-slot="popover-close" className={cn(slots.close(), className)} {...props}>
      {children ?? (
        <>
          <X className={slots.closeIcon()} />
          <span className={slots.srOnly()}>Close</span>
        </>
      )}
    </Popover.Close>
  );
}

// packages/svelte/src/lib/components/popover/popover-close.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Popover as PopoverPrimitive } from "bits-ui";
import { getPopoverContext } from "./popover.context";

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: PopoverPrimitive.CloseProps = $props();

const { slots } = getPopoverContext();
</script>

<PopoverPrimitive.Close
	bind:ref
	class={cn(slots.close(), className)}
	{...rest}
>
	{@render children?.()}
</PopoverPrimitive.Close>
