// packages/react/src/components/popover/popover-content.tsx
import { cn } from "@adn-ui/core";
import { Popover } from "radix-ui";

import { usePopoverContext } from "./popover-context";

export type PopoverContentProps = React.ComponentProps<typeof Popover.Content>;

export default function PopoverContent({
  align = "center",
  children,
  className,
  sideOffset = 4,
  ...props
}: PopoverContentProps) {
  const { slots } = usePopoverContext();

  return (
    <Popover.Portal>
      <Popover.Content
        data-slot="popover-content"
        align={align}
        sideOffset={sideOffset}
        className={cn(slots.content(), className)}
        {...props}
      >
        {children}
      </Popover.Content>
    </Popover.Portal>
  );
}

// packages/svelte/src/lib/components/popover/popover-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Popover as PopoverPrimitive } from "bits-ui";
import { getPopoverContext } from "./popover.context";

let {
	ref = $bindable(null),
	class: className,
	sideOffset = 4,
	...rest
}: PopoverPrimitive.ContentProps = $props();

const { slots } = getPopoverContext();
</script>

<PopoverPrimitive.Content
	bind:ref
	{sideOffset}
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</PopoverPrimitive.Content>
