// packages/react/src/components/table/table-head.tsx
import { cn } from "@adn-ui/core";

import { useTableContext } from "./table-context";

export type TableHeadProps = React.ComponentProps<"th">;

export default function TableHead({ className, ...props }: TableHeadProps) {
  const { slots } = useTableContext();

  return <th data-slot="table-head" className={cn(slots.head(), className)} {...props} />;
}

// packages/svelte/src/lib/components/table/table-head.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getTableContext } from "./table.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLTableCellElement>> = $props();

const { slots } = getTableContext();
</script>

<th
	bind:this={ref}
	class={cn(slots.head(), className)}
	{...rest}
>
	{@render rest.children?.()}
</th>
