// packages/react/src/components/table/table-cell.tsx
import { cn } from "@adn-ui/core";

import { useTableContext } from "./table-context";

export type TableCellProps = React.ComponentProps<"td">;

export default function TableCell({ className, ...props }: TableCellProps) {
  const { slots } = useTableContext();

  return <td data-slot="table-cell" className={cn(slots.cell(), className)} {...props} />;
}

// packages/svelte/src/lib/components/table/table-cell.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getTableContext } from "./table.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLTableCellElement>> = $props();

const { slots } = getTableContext();
</script>

<td
	bind:this={ref}
	class={cn(slots.cell(), className)}
	{...rest}
>
	{@render rest.children?.()}
</td>
