// src/components/ui/table/table-footer.tsx
import { cn } from "tailwind-variants";

import { useTableContext } from "./table.context";

export type TableFooterProps = React.ComponentProps<"tfoot">;

export const TableFooter = ({ children, className, ...props }: TableFooterProps) => {
  const { slots } = useTableContext();
  return (
    <tfoot className={cn(slots.footer(), className)} {...props}>
      {children}
    </tfoot>
  );
};

// packages/svelte/src/lib/components/table/table-footer.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getTableContext } from "./table.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLTableSectionElement>> = $props();

const { slots } = getTableContext();
</script>

<tfoot
	bind:this={ref}
	class={cn(slots.footer(), className)}
	{...rest}
>
	{@render rest.children?.()}
</tfoot>
