// packages/react/src/components/card/card-content.tsx
import { cn } from "@adn-ui/core";

import { useCardContext } from "./card-context";

export type CardContentProps = React.ComponentProps<"div">;

export default function CardContent({ className, ...props }: CardContentProps) {
  const { slots } = useCardContext();
  return <div data-slot="card-content" className={cn(slots.content(), className)} {...props} />;
}

// packages/svelte/src/lib/components/card/card-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getCardContext } from "./card.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

const { slots } = getCardContext();
</script>

<div
	bind:this={ref}
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>
