// packages/react/src/components/card/card-description.tsx
import { cn } from "@adn-ui/core";

import { useCardContext } from "./card-context";

export type CardDescriptionProps = React.ComponentProps<"p">;

export default function CardDescription({ className, ...props }: CardDescriptionProps) {
  const { slots } = useCardContext();

  return (
    <p data-slot="card-description" className={cn(slots.description(), className)} {...props} />
  );
}

// packages/svelte/src/lib/components/card/card-description.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getCardContext } from "./card.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLParagraphElement>> = $props();

const { slots } = getCardContext();
</script>

<p
	bind:this={ref}
	class={cn(slots.description(), className)}
	{...rest}
>
	{@render rest.children?.()}
</p>
