// packages/svelte/src/lib/components/table/table-header.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getTableContext } from "./table.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLTableSectionElement>> = $props();

const { slots } = getTableContext();
</script>

<thead
	bind:this={ref}
	class={cn(slots.header(), className)}
	{...rest}
>
	{@render rest.children?.()}
</thead>

// src/components/ui/table/table-header.tsx
import { cn } from "tailwind-variants";

import { useTableContext } from "./table.context";

export type TableHeaderProps = React.ComponentProps<"thead">;

export const TableHeader = ({ children, className, ...props }: TableHeaderProps) => {
  const { slots } = useTableContext();
  return (
    <thead className={cn(slots.header(), className)} {...props}>
      {children}
    </thead>
  );
};
