// packages/svelte/src/lib/components/card/card-header.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getCardContext } from "./card.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

const { slots } = getCardContext();
</script>

<div
	bind:this={ref}
	class={cn(slots.header(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>

// packages/react/src/components/card/card-header.tsx
import { cn } from "@adn-ui/core";

import { useCardContext } from "./card-context";

export type CardHeaderProps = React.ComponentProps<"div">;

export default function CardHeader({ className, ...props }: CardHeaderProps) {
  const { slots } = useCardContext();

  return <div data-slot="card-header" className={cn(slots.header(), className)} {...props} />;
}
