// packages/svelte/src/lib/components/card/card-title.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getCardContext } from "./card.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLHeadingElement>> = $props();

const { slots } = getCardContext();
</script>

<h3
	bind:this={ref}
	class={cn(slots.title(), className)}
	{...rest}
>
	{@render rest.children?.()}
</h3>

// packages/react/src/components/card/card-title.tsx
import { cn } from "@adn-ui/core";

import { useCardContext } from "./card-context";

export type CardTitleProps = React.ComponentProps<"h2">;

export default function CardTitle({ className, ...props }: CardTitleProps) {
  const { slots } = useCardContext();

  return <h2 data-slot="card-title" className={cn(slots.title(), className)} {...props} />;
}
