// packages/svelte/src/lib/components/table/table-row.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getTableContext } from "./table.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLTableRowElement>> = $props();

const { slots } = getTableContext();
</script>

<tr
	bind:this={ref}
	class={cn(slots.row(), className)}
	{...rest}
>
	{@render rest.children?.()}
</tr>

// packages/react/src/components/table/table-row.tsx
import { cn } from "@adn-ui/core";

import { useTableContext } from "./table-context";

export type TableRowProps = React.ComponentProps<"tr">;

export default function TableRow({ className, ...props }: TableRowProps) {
  const { slots } = useTableContext();

  return <tr data-slot="table-row" className={cn(slots.row(), className)} {...props} />;
}
