// packages/svelte/src/lib/components/table/table-footer.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getTableContext } from "./table.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLTableSectionElement>> = $props();

const { slots } = getTableContext();
</script>

<tfoot
	bind:this={ref}
	class={cn(slots.footer(), className)}
	{...rest}
>
	{@render rest.children?.()}
</tfoot>

// packages/react/src/components/table/table-footer.tsx
import { cn } from "@adn-ui/core";

import { useTableContext } from "./table-context";

export type TableFooterProps = React.ComponentProps<"tfoot">;

export default function TableFooter({ className, ...props }: TableFooterProps) {
  const { slots } = useTableContext();

  return <tfoot data-slot="table-footer" className={cn(slots.footer(), className)} {...props} />;
}
