// packages/svelte/src/lib/components/table/table-body.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getTableContext } from "./table.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLTableSectionElement>> = $props();

const { slots } = getTableContext();
</script>

<tbody
	bind:this={ref}
	class={cn(slots.body(), className)}
	{...rest}
>
	{@render rest.children?.()}
</tbody>

// packages/react/src/components/table/table-body.tsx
import { cn } from "@adn-ui/core";

import { useTableContext } from "./table-context";

export type TableBodyProps = React.ComponentProps<"tbody">;

export default function TableBody({ className, ...props }: TableBodyProps) {
  const { slots } = useTableContext();

  return <tbody data-slot="table-body" className={cn(slots.body(), className)} {...props} />;
}
