// packages/react/src/components/breadcrumb/breadcrumb-link.tsx
import { cn } from "@adn-ui/core";

import { useBreadcrumbContext } from "./breadcrumb-context";

export type BreadcrumbLinkProps = React.ComponentProps<"a">;

export default function BreadcrumbLink({ className, ...props }: BreadcrumbLinkProps) {
  const { slots } = useBreadcrumbContext();

  return <a data-slot="breadcrumb-link" className={cn(slots.link(), className)} {...props} />;
}

// packages/svelte/src/lib/components/breadcrumb/breadcrumb-link.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAnchorAttributes } from "svelte/elements";
import { getBreadcrumbContext } from "./breadcrumb.context";

interface Props extends WithElementRef<HTMLAnchorAttributes> {}

let {
	ref = $bindable(null),
	children,
	class: className,
	...rest
}: Props = $props();

const { slots } = getBreadcrumbContext();
</script>

<a
	bind:this={ref}
	class={cn(slots.link(), className)}
	{...rest}
>
	{@render children?.()}
</a>
