// packages/react/src/components/breadcrumb/breadcrumb-item.tsx
import { cn } from "@adn-ui/core";

import { useBreadcrumbContext } from "./breadcrumb-context";

export type BreadcrumbItemProps = React.ComponentProps<"li">;

export default function BreadcrumbItem({ className, ...props }: BreadcrumbItemProps) {
  const { slots } = useBreadcrumbContext();

  return <li data-slot="breadcrumb-item" className={cn(slots.item(), className)} {...props} />;
}

// packages/svelte/src/lib/components/breadcrumb/breadcrumb-item.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLLIAttributes } from "svelte/elements";
import { getBreadcrumbContext } from "./breadcrumb.context";

interface Props extends WithElementRef<HTMLLIAttributes> {}

let {
	ref = $bindable(null),
	children,
	class: className,
	...rest
}: Props = $props();

const { slots } = getBreadcrumbContext();
</script>

<li
	bind:this={ref}
	class={cn(slots.item(), className)}
	{...rest}
>
	{@render children?.()}
</li>
