// packages/react/src/components/breadcrumb/breadcrumb-root.tsx
import { breadcrumbVariants } from "@adn-ui/core";
import { cn } from "@adn-ui/core";

import { BreadcrumbContext } from "./breadcrumb-context";

export type BreadcrumbRootProps = React.ComponentProps<"nav">;

export default function BreadcrumbRoot({ className, ...props }: BreadcrumbRootProps) {
  const slots = breadcrumbVariants();

  return (
    <BreadcrumbContext value={{ slots }}>
      <nav
        data-slot="breadcrumb"
        aria-label="breadcrumb"
        className={cn(slots.root(), className)}
        {...props}
      />
    </BreadcrumbContext>
  );
}

// packages/svelte/src/lib/components/breadcrumb/breadcrumb-root.svelte
<script lang="ts">
import { breadcrumbVariants, cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { setBreadcrumbContext } from "./breadcrumb.context";

interface Props extends WithElementRef<HTMLAttributes<HTMLElement>> {}

let {
	ref = $bindable(null),
	children,
	class: className,
	...rest
}: Props = $props();

const slots = breadcrumbVariants();
setBreadcrumbContext({ slots });
</script>

<nav
	bind:this={ref}
	aria-label="breadcrumb"
	class={cn(slots.root(), className)}
	{...rest}
>
	{@render children?.()}
</nav>
