// src/components/ui/breadcrumb/breadcrumb-separator.tsx
import { ChevronRight } from "lucide-react";
import { cn } from "tailwind-variants";

import { useBreadcrumbContext } from "./breadcrumb.context";

export type BreadcrumbSeparatorProps = React.ComponentProps<"li">;

export const BreadcrumbSeparator = ({ children, className, ...props }: BreadcrumbSeparatorProps) => {
  const { slots } = useBreadcrumbContext();
  return (
    <li aria-hidden="true" className={cn(slots.separator(), className)} role="presentation" {...props}>
      {children ?? <ChevronRight className="size-3.5" />}
    </li>
  );
};

// packages/svelte/src/lib/components/breadcrumb/breadcrumb-separator.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import { LucideChevronRight } from "lucide-svelte";
import type { HTMLLIAttributes } from "svelte/elements";
import { getBreadcrumbContext } from "./breadcrumb.context";

interface Props extends WithElementRef<HTMLLIAttributes> {}

let {
	ref = $bindable(null),
	children,
	class: className,
	...rest
}: Props = $props();

const { slots } = getBreadcrumbContext();
</script>

<li
	bind:this={ref}
	role="presentation"
	aria-hidden="true"
	class={cn(slots.separator(), className)}
	{...rest}
>
	{#if children}
		{@render children()}
	{:else}
		<LucideChevronRight class="size-3.5" />
	{/if}
</li>
