// packages/react/src/components/collapsible/collapsible-trigger.tsx
import { cn } from "@adn-ui/core";
import { Collapsible } from "radix-ui";

import { useCollapsibleContext } from "./collapsible-context";

export type CollapsibleTriggerProps = React.ComponentProps<typeof Collapsible.Trigger>;

export default function CollapsibleTrigger({ className, ...props }: CollapsibleTriggerProps) {
  const { slots } = useCollapsibleContext();

  return (
    <Collapsible.Trigger
      data-slot="collapsible-trigger"
      className={cn(slots.trigger(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/collapsible/collapsible-trigger.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Collapsible as CollapsiblePrimitive } from "bits-ui";
import { getCollapsibleContext } from "./collapsible.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: CollapsiblePrimitive.TriggerProps = $props();

const { slots } = getCollapsibleContext();
</script>

<CollapsiblePrimitive.Trigger
	bind:ref
	class={cn(slots.trigger(), className)}
	{...rest}
/>
