// packages/react/src/components/collapsible/collapsible-content.tsx
import { cn } from "@adn-ui/core";
import { Collapsible } from "radix-ui";

import { useCollapsibleContext } from "./collapsible-context";

export type CollapsibleContentProps = React.ComponentProps<typeof Collapsible.Content>;

export default function CollapsibleContent({
  children,
  className,
  ...props
}: CollapsibleContentProps) {
  const { slots } = useCollapsibleContext();

  return (
    <Collapsible.Content
      data-slot="collapsible-content"
      className={cn(slots.content(), className)}
      {...props}
    >
      {children}
    </Collapsible.Content>
  );
}

// packages/svelte/src/lib/components/collapsible/collapsible-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Collapsible as CollapsiblePrimitive } from "bits-ui";
import { getCollapsibleContext } from "./collapsible.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: CollapsiblePrimitive.ContentProps = $props();

const { slots } = getCollapsibleContext();
</script>

<CollapsiblePrimitive.Content
	bind:ref
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</CollapsiblePrimitive.Content>
