// packages/react/src/components/dialog/dialog-title.tsx
import { cn } from "@adn-ui/core";
import { Dialog } from "radix-ui";

import { useDialogContext } from "./dialog-context";

export type DialogTitleProps = React.ComponentProps<typeof Dialog.Title>;

export default function DialogTitle({ className, ...props }: DialogTitleProps) {
  const { slots } = useDialogContext();

  return (
    <Dialog.Title data-slot="dialog-title" className={cn(slots.title(), className)} {...props} />
  );
}

// packages/svelte/src/lib/components/dialog/dialog-title.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Dialog as DialogPrimitive } from "bits-ui";
import { getDialogContext } from "./dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DialogPrimitive.TitleProps = $props();

const { slots } = getDialogContext();
</script>

<DialogPrimitive.Title
	bind:ref
	class={cn(slots.title(), className)}
	{...rest}
/>
