// packages/react/src/components/select/select-trigger.tsx
import { cn } from "@adn-ui/core";
import { ChevronDown } from "lucide-react";
import { Select } from "radix-ui";

import { useSelectContext } from "./select-context";

export type SelectTriggerProps = React.ComponentProps<typeof Select.Trigger>;

export default function SelectTrigger({ children, className, ...props }: SelectTriggerProps) {
  const { slots } = useSelectContext();

  return (
    <Select.Trigger
      data-slot="select-trigger"
      className={cn(slots.trigger(), className)}
      {...props}
    >
      {children}
      <Select.Icon asChild>
        <ChevronDown className={slots.icon()} />
      </Select.Icon>
    </Select.Trigger>
  );
}

// packages/svelte/src/lib/components/select/select-trigger.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Select as SelectPrimitive } from "bits-ui";
import ChevronDown from "lucide-svelte/icons/chevron-down";
import { getSelectContext } from "./select.context.js";

let {
	ref = $bindable(null),
	class: className,
	placeholder = "Select...",
	...rest
}: SelectPrimitive.TriggerProps & { placeholder?: string } = $props();

const context = getSelectContext();
</script>

<SelectPrimitive.Trigger
	bind:ref
	class={cn(context.slots.trigger(), className)}
	{...rest}
>
	{#if rest.children}
		{@render rest.children()}
	{:else}
		<SelectPrimitive.Value {placeholder} />
	{/if}
	<ChevronDown class={context.slots.icon()} aria-hidden="true" />
</SelectPrimitive.Trigger>
