// packages/svelte/src/lib/components/input/input.svelte
<script lang="ts">
import { cn, type InputVariants, inputVariants } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLInputAttributes } from "svelte/elements";

interface Props extends WithElementRef<HTMLInputAttributes>, InputVariants {}

let {
	ref = $bindable(null),
	value = $bindable(),
	class: className,
	size = "md",
	...rest
}: Props = $props();
</script>

<input
	bind:this={ref}
	bind:value
	class={cn(inputVariants({ size }), className)}
	{...rest}
/>

// packages/react/src/components/input/input.tsx
import { type InputVariants, inputVariants } from "@adn-ui/core";

export type InputProps = Omit<React.ComponentProps<"input">, "size"> &
	InputVariants;

export default function Input({ size, className, ...props }: InputProps) {
	const styles = inputVariants({ size, className });

	return <input data-slot="input" className={styles} {...props} />;
}
