// packages/svelte/src/lib/components/alert-dialog/alert-dialog-root.svelte
<script lang="ts">
import { alertDialogVariants } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { setAlertDialogContext } from "./alert-dialog.context";

let { open = $bindable(false), ...rest }: AlertDialogPrimitive.RootProps =
	$props();

const slots = alertDialogVariants();
setAlertDialogContext({ slots });
</script>

<AlertDialogPrimitive.Root bind:open {...rest}>
	{@render rest.children?.()}
</AlertDialogPrimitive.Root>

// packages/react/src/components/alert-dialog/alert-dialog-root.tsx
import { alertDialogVariants } from "@adn-ui/core";
import { AlertDialog } from "radix-ui";

import { AlertDialogContext } from "./alert-dialog-context";

export type AlertDialogRootProps = React.ComponentProps<typeof AlertDialog.Root>;

export default function AlertDialogRoot(props: AlertDialogRootProps) {
  const slots = alertDialogVariants();

  return (
    <AlertDialogContext value={{ slots }}>
      <AlertDialog.Root {...props} />
    </AlertDialogContext>
  );
}
