// packages/svelte/src/lib/components/alert-dialog/alert-dialog-footer.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

const { slots } = getAlertDialogContext();
</script>

<div
	bind:this={ref}
	class={cn(slots.footer(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>

// packages/react/src/components/alert-dialog/alert-dialog-footer.tsx
import { cn } from "@adn-ui/core";

import { useAlertDialogContext } from "./alert-dialog-context";

export type AlertDialogFooterProps = React.ComponentProps<"div">;

export default function AlertDialogFooter({ className, ...props }: AlertDialogFooterProps) {
  const { slots } = useAlertDialogContext();

  return (
    <div data-slot="alert-dialog-footer" className={cn(slots.footer(), className)} {...props} />
  );
}
