// packages/svelte/src/lib/components/field/field-description.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getFieldContext } from "./field.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLParagraphElement>> = $props();

const { slots } = getFieldContext();
</script>

<p
	bind:this={ref}
	class={cn(slots.description(), className)}
	{...rest}
>
	{@render rest.children?.()}
</p>

// packages/react/src/components/field/field-description.tsx
export type FieldDescriptionProps = React.HTMLAttributes<HTMLParagraphElement>;

import { useFieldContext } from "./field.context";

export const FieldDescription = ({
	className,
	...props
}: FieldDescriptionProps) => {
	const { id, slots } = useFieldContext();
	return (
		<p
			id={`${id}-description`}
			className={slots.description({ class: className })}
			{...props}
		/>
	);
};
