// packages/react/src/components/switch/index.ts
import SwitchRoot from "./switch-root";
import SwitchThumb from "./switch-thumb";

export const Switch = {
	Root: SwitchRoot,
	Thumb: SwitchThumb,
};

export { SwitchRoot, SwitchThumb };

export type SwitchRootProps = React.ComponentProps<typeof SwitchRoot>;
export type SwitchThumbProps = React.ComponentProps<typeof SwitchThumb>;

export { type SwitchVariants, switchVariants } from "@adn-ui/core";

// packages/svelte/src/lib/components/switch/switch.svelte
<script lang="ts">
import { cn, type SwitchVariants, switchVariants } from "@adn-ui/core";
import { Switch as SwitchPrimitive } from "bits-ui";

let {
	ref = $bindable(null),
	checked = $bindable(false),
	class: className,
	size = "md",
	...rest
}: SwitchPrimitive.RootProps & SwitchVariants = $props();

const slots = $derived(switchVariants({ size }));
</script>

<SwitchPrimitive.Root
	bind:ref
	bind:checked
	class={cn(slots.root(), className)}
	{...rest}
>
	<SwitchPrimitive.Thumb class={slots.thumb()} />
</SwitchPrimitive.Root>
