// packages/react/src/components/alert-dialog/alert-dialog-title.tsx
import { cn } from "@adn-ui/core";
import { AlertDialog } from "radix-ui";

import { useAlertDialogContext } from "./alert-dialog-context";

export type AlertDialogTitleProps = React.ComponentProps<typeof AlertDialog.Title>;

export default function AlertDialogTitle({ className, ...props }: AlertDialogTitleProps) {
  const { slots } = useAlertDialogContext();

  return (
    <AlertDialog.Title
      data-slot="alert-dialog-title"
      className={cn(slots.title(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/alert-dialog/alert-dialog-title.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.TitleProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Title
	bind:ref
	class={cn(slots.title(), className)}
	{...rest}
/>
