// packages/react/src/components/alert-dialog/alert-dialog-action.tsx
import { buttonVariants } from "@adn-ui/core";
import { cn } from "@adn-ui/core";
import { AlertDialog } from "radix-ui";

export type AlertDialogActionProps = React.ComponentProps<typeof AlertDialog.Action>;

export default function AlertDialogAction({ className, ...props }: AlertDialogActionProps) {
  return (
    <AlertDialog.Action
      data-slot="alert-dialog-action"
      className={cn(buttonVariants(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/alert-dialog/alert-dialog-action.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.ActionProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Action
	bind:ref
	class={cn(slots.action(), className)}
	{...rest}
/>
