// packages/react/src/components/alert-dialog/alert-dialog-overlay.tsx
import { cn } from "@adn-ui/core";
import { AlertDialog } from "radix-ui";

import { useAlertDialogContext } from "./alert-dialog-context";

export type AlertDialogOverlayProps = React.ComponentProps<typeof AlertDialog.Overlay>;

export default function AlertDialogOverlay({ className, ...props }: AlertDialogOverlayProps) {
  const { slots } = useAlertDialogContext();

  return (
    <AlertDialog.Overlay
      data-slot="alert-dialog-overlay"
      className={cn(slots.overlay(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/alert-dialog/alert-dialog-overlay.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.OverlayProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Overlay
	bind:ref
	class={cn(slots.overlay(), className)}
	{...rest}
/>
