// src/components/ui/alert-dialog/alert-dialog-action.tsx
import { AlertDialog } from "radix-ui";
import { cn } from "tailwind-variants";

import { useAlertDialogContext } from "./alert-dialog.context";

export type AlertDialogActionProps = React.ComponentProps<typeof AlertDialog.Action>;

export const AlertDialogAction = ({ className, ...props }: AlertDialogActionProps) => {
  const { slots } = useAlertDialogContext();

  return <AlertDialog.Action className={cn(slots.action(), className)} {...props} />;
};

// packages/svelte/src/lib/components/alert-dialog/alert-dialog-action.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.ActionProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Action
	bind:ref
	class={cn(slots.action(), className)}
	{...rest}
/>
