// src/components/ui/alert-dialog/alert-dialog-cancel.tsx
import { AlertDialog } from "radix-ui";
import { cn } from "tailwind-variants";

import { useAlertDialogContext } from "./alert-dialog.context";

export type AlertDialogCancelProps = React.ComponentProps<typeof AlertDialog.Cancel>;

export const AlertDialogCancel = ({ className, ...props }: AlertDialogCancelProps) => {
  const { slots } = useAlertDialogContext();

  return <AlertDialog.Cancel className={cn(slots.cancel(), className)} {...props} />;
};

// packages/svelte/src/lib/components/alert-dialog/alert-dialog-cancel.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.CancelProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Cancel
	bind:ref
	class={cn(slots.cancel(), className)}
	{...rest}
/>
