// packages/react/src/components/alert-dialog/alert-dialog-description.tsx
import { cn } from "@adn-ui/core";
import { AlertDialog } from "radix-ui";

import { useAlertDialogContext } from "./alert-dialog-context";

export type AlertDialogDescriptionProps = React.ComponentProps<typeof AlertDialog.Description>;

export default function AlertDialogDescription({
  className,
  ...props
}: AlertDialogDescriptionProps) {
  const { slots } = useAlertDialogContext();

  return (
    <AlertDialog.Description
      data-slot="alert-dialog-description"
      className={cn(slots.description(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/alert-dialog/alert-dialog-description.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.DescriptionProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Description
	bind:ref
	class={cn(slots.description(), className)}
	{...rest}
/>
