// packages/react/src/components/alert-dialog/alert-dialog-content.tsx
import { cn } from "@adn-ui/core";
import { AlertDialog } from "radix-ui";

import { useAlertDialogContext } from "./alert-dialog-context";
import AlertDialogOverlay from "./alert-dialog-overlay";

export type AlertDialogContentProps = React.ComponentProps<typeof AlertDialog.Content>;

export default function AlertDialogContent({
  children,
  className,
  ...props
}: AlertDialogContentProps) {
  const { slots } = useAlertDialogContext();

  return (
    <AlertDialog.Portal>
      <AlertDialogOverlay />
      <AlertDialog.Content
        data-slot="alert-dialog-content"
        className={cn(slots.content(), className)}
        {...props}
      >
        {children}
      </AlertDialog.Content>
    </AlertDialog.Portal>
  );
}

// packages/svelte/src/lib/components/alert-dialog/alert-dialog-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
import { getAlertDialogContext } from "./alert-dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AlertDialogPrimitive.ContentProps = $props();

const { slots } = getAlertDialogContext();
</script>

<AlertDialogPrimitive.Content
	bind:ref
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</AlertDialogPrimitive.Content>
