// packages/svelte/src/lib/components/alert/alert-description.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getAlertContext } from "./alert.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

const { slots } = getAlertContext();
</script>

<div
	bind:this={ref}
	class={cn(slots.description(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>

// packages/react/src/components/alert/alert-description.tsx
import { cn } from "@adn-ui/core";

import { useAlertContext } from "./alert-context";

export type AlertDescriptionProps = React.ComponentProps<"div">;

export default function AlertDescription({ className, ...props }: AlertDescriptionProps) {
  const { slots } = useAlertContext();

  return (
    <div data-slot="alert-description" className={cn(slots.description(), className)} {...props} />
  );
}
