// packages/svelte/src/lib/components/alert/alert-root.svelte
<script lang="ts">
import { type AlertVariants, alertVariants, cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { setAlertContext } from "./alert.context";

interface Props
	extends WithElementRef<HTMLAttributes<HTMLDivElement>>,
		AlertVariants {}

let {
	ref = $bindable(null),
	class: className,
	variant = "default",
	...rest
}: Props = $props();

const slots = $derived(alertVariants({ variant }));
setAlertContext({
	get slots() {
		return slots;
	},
});
</script>

<div
	bind:this={ref}
	role="alert"
	class={cn(slots.root(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>

// packages/react/src/components/alert/alert-root.tsx
import { type AlertVariants, alertVariants } from "@adn-ui/core";
import { cn } from "@adn-ui/core";

import { AlertContext } from "./alert-context";

export type AlertRootProps = React.ComponentProps<"div"> & AlertVariants;

export default function AlertRoot({ className, variant, ...props }: AlertRootProps) {
  const slots = alertVariants({ variant });

  return (
    <AlertContext value={{ slots }}>
      <div data-slot="alert" role="alert" className={cn(slots.root(), className)} {...props} />
    </AlertContext>
  );
}
