// packages/svelte/src/lib/components/progress/progress-root.svelte
<script lang="ts">
import { cn, progressVariants } from "@adn-ui/core";
import { Progress as ProgressPrimitive } from "bits-ui";
import { setProgressContext } from "./progress.context";

let {
	ref = $bindable(null),
	value = $bindable(0),
	max = 100,
	class: className,
	...rest
}: ProgressPrimitive.RootProps = $props();

const slots = progressVariants();
setProgressContext({ slots });
</script>

<ProgressPrimitive.Root
	bind:ref
	bind:value
	{max}
	class={cn(slots.root(), className)}
	{...rest}
/>

// packages/react/src/components/progress/progress-root.tsx
import { type ProgressVariants, progressVariants } from "@adn-ui/core";
import { Progress } from "radix-ui";

import { ProgressContext } from "./progress-context";

export type ProgressRootProps = React.ComponentProps<typeof Progress.Root> &
	ProgressVariants;

export default function ProgressRoot({
	className,
	size,
	...props
}: ProgressRootProps) {
	const slots = progressVariants({ size });

	return (
		<ProgressContext value={{ slots }}>
			<Progress.Root
				data-slot="progress"
				className={slots.root({ className })}
				{...props}
			/>
		</ProgressContext>
	);
}
