// packages/svelte/src/lib/components/avatar/avatar-root.svelte
<script lang="ts">
import { avatarVariants, cn } from "@adn-ui/core";
import { Avatar as AvatarPrimitive } from "bits-ui";
import { setAvatarContext } from "./avatar.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AvatarPrimitive.RootProps = $props();

const slots = avatarVariants();
setAvatarContext({ slots });
</script>

<AvatarPrimitive.Root
	bind:ref
	class={cn(slots.root(), className)}
	{...rest}
/>

// packages/react/src/components/avatar/avatar-root.tsx
import { type AvatarVariants, avatarVariants } from "@adn-ui/core";
import { Avatar } from "radix-ui";
import { AvatarContext } from "./avatar-context";

export type AvatarRootProps = React.ComponentProps<typeof Avatar.Root> &
	AvatarVariants;

export default function AvatarRoot({
	size,
	className,
	...props
}: AvatarRootProps) {
	const slots = avatarVariants({ size });

	return (
		<AvatarContext value={{ slots }}>
			<Avatar.Root className={slots.root({ className })} {...props} />
		</AvatarContext>
	);
}
