// packages/react/src/components/radio-group/radio-group-root.tsx
import { radioGroupVariants } from "@adn-ui/core";
import { cn } from "@adn-ui/core";
import { RadioGroup } from "radix-ui";

import { RadioGroupContext } from "./radio-group-context";

export type RadioGroupRootProps = React.ComponentProps<typeof RadioGroup.Root>;

export default function RadioGroupRoot({ className, ...props }: RadioGroupRootProps) {
  const slots = radioGroupVariants();

  return (
    <RadioGroupContext value={{ slots }}>
      <RadioGroup.Root
        data-slot="radio-group-root"
        className={cn(slots.root(), className)}
        {...props}
      />
    </RadioGroupContext>
  );
}

// packages/svelte/src/lib/components/radio-group/radio-group-root.svelte
<script lang="ts">
import { cn, radioGroupVariants } from "@adn-ui/core";
import { RadioGroup as RadioGroupPrimitive } from "bits-ui";
import { setRadioGroupContext } from "./radio-group.context";

let {
	ref = $bindable(null),
	value = $bindable(),
	class: className,
	...rest
}: RadioGroupPrimitive.RootProps = $props();

const slots = radioGroupVariants();
setRadioGroupContext({ slots });
</script>

<RadioGroupPrimitive.Root
	bind:ref
	bind:value
	class={cn(slots.root(), className)}
	{...rest}
/>
