// packages/svelte/src/lib/components/separator/separator.svelte
<script lang="ts">
import { cn, type SeparatorVariants, separatorVariants } from "@adn-ui/core";
import { Separator as SeparatorPrimitive } from "bits-ui";

let {
	ref = $bindable(null),
	class: className,
	orientation = "horizontal",
	decorative = true,
	...rest
}: SeparatorPrimitive.RootProps & SeparatorVariants = $props();
</script>

<SeparatorPrimitive.Root
	bind:ref
	{orientation}
	{decorative}
	class={cn(separatorVariants({ orientation }), className)}
	{...rest}
/>

// packages/react/src/components/separator/separator.tsx
import { separatorVariants } from "@adn-ui/core";
import { Separator } from "radix-ui";

export type SeparatorProps = React.ComponentProps<typeof Separator.Root>;

export default function SeparatorRoot({
  className,
  decorative = true,
  orientation = "horizontal",
  ...props
}: SeparatorProps) {
  const styles = separatorVariants({ className, orientation });

  return (
    <Separator.Root
      data-slot="separator"
      decorative={decorative}
      orientation={orientation}
      className={styles}
      {...props}
    />
  );
}
