// packages/svelte/src/lib/components/accordion/accordion-trigger.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Accordion as AccordionPrimitive } from "bits-ui";
import { LucideChevronDown } from "lucide-svelte";
import { getAccordionContext } from "./accordion.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: AccordionPrimitive.TriggerProps = $props();

const { slots } = getAccordionContext();
</script>

<AccordionPrimitive.Trigger
	bind:ref
	class={cn(slots.trigger(), className)}
	{...rest}
>
	{@render rest.children?.()}
	<LucideChevronDown class={slots.chevron()} aria-hidden="true" />
</AccordionPrimitive.Trigger>

// src/components/ui/accordion/accordion-trigger.tsx
import { ChevronDown } from "lucide-react";
import { Accordion } from "radix-ui";
import { cn } from "tailwind-variants";

import { useAccordionContext } from "./accordion.context";

export type AccordionTriggerProps = React.ComponentProps<typeof Accordion.Trigger>;

export const AccordionTrigger = ({ children, className, ...props }: AccordionTriggerProps) => {
  const { slots } = useAccordionContext();

  return (
    <Accordion.Header className={slots.header()}>
      <Accordion.Trigger className={cn(slots.trigger(), className)} {...props}>
        {children}
        <ChevronDown aria-hidden className={slots.chevron()} />
      </Accordion.Trigger>
    </Accordion.Header>
  );
};
