// packages/svelte/src/lib/components/collapsible/collapsible-root.svelte
<script lang="ts">
import { collapsibleVariants } from "@adn-ui/core";
import { Collapsible as CollapsiblePrimitive } from "bits-ui";
import { setCollapsibleContext } from "./collapsible.context";

let {
	ref = $bindable(null),
	open = $bindable(false),
	...rest
}: CollapsiblePrimitive.RootProps = $props();

const slots = collapsibleVariants();
setCollapsibleContext({ slots });
</script>

<CollapsiblePrimitive.Root bind:ref bind:open {...rest}>
	{@render rest.children?.()}
</CollapsiblePrimitive.Root>

// packages/react/src/components/collapsible/collapsible-root.tsx
import { collapsibleVariants } from "@adn-ui/core";
import { cn } from "@adn-ui/core";
import { Collapsible } from "radix-ui";

import { CollapsibleContext } from "./collapsible-context";

export type CollapsibleRootProps = React.ComponentProps<typeof Collapsible.Root>;

export default function CollapsibleRoot({ className, ...props }: CollapsibleRootProps) {
  const slots = collapsibleVariants();

  return (
    <CollapsibleContext value={{ slots }}>
      <Collapsible.Root
        data-slot="collapsible-root"
        className={cn(slots.root(), className)}
        {...props}
      />
    </CollapsibleContext>
  );
}
