// packages/svelte/src/lib/components/context-menu/context-menu-item.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { getContextMenuContext } from "./context-menu.context";

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: ContextMenuPrimitive.ItemProps = $props();

const context = getContextMenuContext();
</script>

<ContextMenuPrimitive.Item
	bind:ref
	class={cn(context.slots.item(), className)}
	{...rest}
>
	{@render children?.()}
</ContextMenuPrimitive.Item>

// packages/react/src/components/context-menu/context-menu-item.tsx
import { cn } from "@adn-ui/core";
import { ContextMenu } from "radix-ui";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuItemProps = React.ComponentProps<typeof ContextMenu.Item>;

export default function ContextMenuItem({ className, ...props }: ContextMenuItemProps) {
  const { slots } = useContextMenuContext();

  return (
    <ContextMenu.Item
      data-slot="context-menu-item"
      className={cn(slots.item(), className)}
      {...props}
    />
  );
}
