// packages/svelte/src/lib/components/context-menu/context-menu-shortcut.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getContextMenuContext } from "./context-menu.context";

interface Props extends WithElementRef<HTMLAttributes<HTMLSpanElement>> {}

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: Props = $props();

const context = getContextMenuContext();
</script>

<span
	bind:this={ref}
	class={cn(context.slots.shortcut(), className)}
	{...rest}
>
	{@render children?.()}
</span>

// packages/react/src/components/context-menu/context-menu-shortcut.tsx
import { cn } from "@adn-ui/core";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuShortcutProps = React.ComponentProps<"span">;

export default function ContextMenuShortcut({ className, ...props }: ContextMenuShortcutProps) {
  const { slots } = useContextMenuContext();

  return (
    <span
      data-slot="context-menu-shortcut"
      className={cn(slots.shortcut(), className)}
      {...props}
    />
  );
}
