// packages/svelte/src/lib/components/context-menu/context-menu-separator.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { getContextMenuContext } from "./context-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: ContextMenuPrimitive.SeparatorProps = $props();

const context = getContextMenuContext();
</script>

<ContextMenuPrimitive.Separator
	bind:ref
	class={cn(context.slots.separator(), className)}
	{...rest}
/>

// packages/react/src/components/context-menu/context-menu-separator.tsx
import { cn } from "@adn-ui/core";
import { ContextMenu } from "radix-ui";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuSeparatorProps = React.ComponentProps<typeof ContextMenu.Separator>;

export default function ContextMenuSeparator({ className, ...props }: ContextMenuSeparatorProps) {
  const { slots } = useContextMenuContext();

  return (
    <ContextMenu.Separator
      data-slot="context-menu-separator"
      className={cn(slots.separator(), className)}
      {...props}
    />
  );
}
