// packages/svelte/src/lib/components/context-menu/context-menu-sub-trigger.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { LucideChevronRight } from "lucide-svelte";
import { getContextMenuContext } from "./context-menu.context";

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: ContextMenuPrimitive.SubTriggerProps = $props();

const context = getContextMenuContext();
</script>

<ContextMenuPrimitive.SubTrigger
	bind:ref
	class={cn(context.slots.subTrigger(), className)}
	{...rest}
>
	{@render children?.()}
	<LucideChevronRight class="ml-auto size-4" />
</ContextMenuPrimitive.SubTrigger>

// packages/react/src/components/context-menu/context-menu-sub-trigger.tsx
import { cn } from "@adn-ui/core";
import { ChevronRight } from "lucide-react";
import { ContextMenu } from "radix-ui";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuSubTriggerProps = React.ComponentProps<typeof ContextMenu.SubTrigger>;

export default function ContextMenuSubTrigger({
  children,
  className,
  ...props
}: ContextMenuSubTriggerProps) {
  const { slots } = useContextMenuContext();

  return (
    <ContextMenu.SubTrigger
      data-slot="context-menu-sub-trigger"
      className={cn(slots.subTrigger(), className)}
      {...props}
    >
      {children}
      <ChevronRight className="ml-auto size-4" />
    </ContextMenu.SubTrigger>
  );
}
