// packages/svelte/src/lib/components/context-menu/context-menu-radio-item.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { LucideCircle } from "lucide-svelte";
import { getContextMenuContext } from "./context-menu.context";

let {
	ref = $bindable(null),
	class: className,
	value,
	...rest
}: ContextMenuPrimitive.RadioItemProps = $props();

const { slots } = getContextMenuContext();
</script>

<ContextMenuPrimitive.RadioItem
	bind:ref
	{value}
	class={cn(slots.item(), className)}
	{...rest}
>
	{#snippet children({ checked })}
		{#if rest.children}
			{@render rest.children({ checked })}
		{:else}
			{@render rest.children?.()}
			<span class={slots.itemIndicator()}>
				{#if checked}
					<LucideCircle class="size-2 fill-current" />
				{/if}
			</span>
		{/if}
	{/snippet}
</ContextMenuPrimitive.RadioItem>

// packages/react/src/components/context-menu/context-menu-radio-item.tsx
import { cn } from "@adn-ui/core";
import { Circle } from "lucide-react";
import { ContextMenu } from "radix-ui";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuRadioItemProps = React.ComponentProps<typeof ContextMenu.RadioItem>;

export default function ContextMenuRadioItem({
  children,
  className,
  ...props
}: ContextMenuRadioItemProps) {
  const { slots } = useContextMenuContext();

  return (
    <ContextMenu.RadioItem
      data-slot="context-menu-radio-item"
      className={cn(slots.radioItem(), className)}
      {...props}
    >
      <ContextMenu.ItemIndicator className={slots.itemIndicator()}>
        <Circle className="size-2 fill-current" />
      </ContextMenu.ItemIndicator>
      {children}
    </ContextMenu.RadioItem>
  );
}
