// packages/svelte/src/lib/components/context-menu/context-menu-label.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
import { getContextMenuContext } from "./context-menu.context";

let {
	ref = $bindable(null),
	class: className,
	children,
	...rest
}: ContextMenuPrimitive.GroupHeadingProps = $props();

const context = getContextMenuContext();
</script>

<ContextMenuPrimitive.GroupHeading
	bind:ref
	class={cn(context.slots.label(), className)}
	{...rest}
>
	{@render children?.()}
</ContextMenuPrimitive.GroupHeading>

// packages/react/src/components/context-menu/context-menu-label.tsx
import { cn } from "@adn-ui/core";
import { ContextMenu } from "radix-ui";

import { useContextMenuContext } from "./context-menu-context";

export type ContextMenuLabelProps = React.ComponentProps<typeof ContextMenu.Label>;

export default function ContextMenuLabel({ className, ...props }: ContextMenuLabelProps) {
  const { slots } = useContextMenuContext();

  return (
    <ContextMenu.Label
      data-slot="context-menu-label"
      className={cn(slots.label(), className)}
      {...props}
    />
  );
}
