// packages/react/src/components/field/field-root.tsx
import { type FieldVariants, fieldVariants } from "@adn-ui/core";
import { useId } from "react";

import { FieldContext } from "./field.context";

export type FieldRootProps = React.HTMLAttributes<HTMLDivElement> & FieldVariants;

export const FieldRoot = ({ className, id, orientation, ...props }: FieldRootProps) => {
  const generatedId = useId();

  const slots = fieldVariants({ orientation });

  return (
    <FieldContext.Provider value={{ id: id || generatedId, slots }}>
      <div className={slots.root({ class: className })} {...props} />
    </FieldContext.Provider>
  );
};

// packages/svelte/src/lib/components/field/field-root.svelte
<script lang="ts">
import { cn, fieldVariants } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { setFieldContext } from "./field.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

const slots = fieldVariants();
setFieldContext({ slots });
</script>

<div
	bind:this={ref}
	class={cn(slots.root(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>
