// packages/react/src/components/field/field-error.tsx
import { useFieldContext } from "./field.context";

export type FieldErrorProps = React.HTMLAttributes<HTMLParagraphElement>;

export const FieldError = ({ className, ...props }: FieldErrorProps) => {
  const { id, slots } = useFieldContext();
  return (
    <p aria-describedby={`${id}-error`} className={slots.error({ class: className })} {...props} />
  );
};

// packages/svelte/src/lib/components/field/field-error.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getFieldContext } from "./field.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLParagraphElement>> = $props();

const { slots } = getFieldContext();
</script>

<p
	bind:this={ref}
	class={cn(slots.error(), className)}
	{...rest}
>
	{@render rest.children?.()}
</p>
