// packages/react/src/components/accordion/accordion-root.tsx
import { accordionVariants } from "@adn-ui/core";
import { cn } from "@adn-ui/core";
import { Accordion } from "radix-ui";

import { AccordionContext } from "./accordion-context";

export type AccordionRootProps = React.ComponentProps<typeof Accordion.Root>;

export default function AccordionRoot({ className, ...props }: AccordionRootProps) {
  const slots = accordionVariants();

  return (
    <AccordionContext value={{ slots }}>
      <Accordion.Root
        data-slot="accordion-root"
        className={cn(slots.root(), className)}
        {...props}
      />
    </AccordionContext>
  );
}

// packages/svelte/src/lib/components/accordion/accordion-root.svelte
<script lang="ts">
import { accordionVariants, cn } from "@adn-ui/core";
import { Accordion as AccordionPrimitive } from "bits-ui";
import { setAccordionContext } from "./accordion.context";
import Accordion from "./accordion.stories.svelte";

let {
	ref = $bindable(null),
	value = $bindable(),
	type,
	class: className,
	...rest
}: AccordionPrimitive.RootProps = $props();

const slots = accordionVariants();
setAccordionContext({ slots });
</script>

	<AccordionPrimitive.Root
		bind:ref
		bind:value
		class={cn(slots.root(), className)}
		{...rest as any}
	/>
