// packages/react/src/components/alert/alert-title.tsx
import { cn } from "@adn-ui/core";

import { useAlertContext } from "./alert-context";

export type AlertTitleProps = React.ComponentProps<"h5">;

export default function AlertTitle({ className, ...props }: AlertTitleProps) {
  const { slots } = useAlertContext();

  return <h5 data-slot="alert-title" className={cn(slots.title(), className)} {...props} />;
}

// packages/svelte/src/lib/components/alert/alert-title.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getAlertContext } from "./alert.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLHeadingElement>> = $props();

const { slots } = getAlertContext();
</script>

<h5
	bind:this={ref}
	class={cn(slots.title(), className)}
	{...rest}
>
	{@render rest.children?.()}
</h5>
