// packages/react/src/components/scroll-area/scroll-area-root.tsx
import { scrollAreaVariants } from "@adn-ui/core";
import { cn } from "@adn-ui/core";
import { ScrollArea } from "radix-ui";

import { ScrollAreaContext } from "./scroll-area-context";

export type ScrollAreaRootProps = React.ComponentProps<typeof ScrollArea.Root>;

export default function ScrollAreaRoot({ className, ...props }: ScrollAreaRootProps) {
  const slots = scrollAreaVariants();

  return (
    <ScrollAreaContext value={{ slots }}>
      <ScrollArea.Root
        data-slot="scroll-area-root"
        className={cn(slots.root(), className)}
        {...props}
      />
    </ScrollAreaContext>
  );
}

// packages/svelte/src/lib/components/scroll-area/scroll-area-root.svelte
<script lang="ts">
import { cn, scrollAreaVariants } from "@adn-ui/core";
import { ScrollArea as ScrollAreaPrimitive } from "bits-ui";
import { setScrollAreaContext } from "./scroll-area.context.js";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: ScrollAreaPrimitive.RootProps = $props();

const slots = scrollAreaVariants();
setScrollAreaContext(slots);
</script>

<ScrollAreaPrimitive.Root
	bind:ref
	class={cn(slots.root(), className)}
	{...rest}
/>
