// packages/react/src/components/scroll-area/scroll-area-corner.tsx
import { cn } from "@adn-ui/core";
import { ScrollArea } from "radix-ui";

import { useScrollAreaContext } from "./scroll-area-context";

export type ScrollAreaCornerProps = React.ComponentProps<typeof ScrollArea.Corner>;

export default function ScrollAreaCorner({ className, ...props }: ScrollAreaCornerProps) {
  const { slots } = useScrollAreaContext();

  return (
    <ScrollArea.Corner
      data-slot="scroll-area-corner"
      className={cn(slots.corner(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/scroll-area/scroll-area-corner.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ScrollArea as ScrollAreaPrimitive } from "bits-ui";
import { getScrollAreaContext } from "./scroll-area.context.js";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: ScrollAreaPrimitive.CornerProps = $props();

const slots = getScrollAreaContext();
</script>

<ScrollAreaPrimitive.Corner
	bind:ref
	class={cn(slots.corner(), className)}
	{...rest}
/>
