// packages/react/src/components/scroll-area/scroll-area-viewport.tsx
import { cn } from "@adn-ui/core";
import { ScrollArea } from "radix-ui";

import { useScrollAreaContext } from "./scroll-area-context";

export type ScrollAreaViewportProps = React.ComponentProps<typeof ScrollArea.Viewport>;

export default function ScrollAreaViewport({ className, ...props }: ScrollAreaViewportProps) {
  const { slots } = useScrollAreaContext();

  return (
    <ScrollArea.Viewport
      data-slot="scroll-area-viewport"
      className={cn(slots.viewport(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/scroll-area/scroll-area-viewport.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { ScrollArea as ScrollAreaPrimitive } from "bits-ui";
import { getScrollAreaContext } from "./scroll-area.context.js";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: ScrollAreaPrimitive.ViewportProps = $props();

const slots = getScrollAreaContext();
</script>

<ScrollAreaPrimitive.Viewport
	bind:ref
	class={cn(slots.viewport(), className)}
	{...rest}
/>
