// packages/react/src/components/tabs/tabs-root.tsx
import { type TabsVariants, tabsVariants } from "@adn-ui/core";
import { Tabs } from "radix-ui";

import { TabsContext } from "./tabs-context";

export type TabsRootProps = React.ComponentProps<typeof Tabs.Root> &
	TabsVariants;

export default function TabsRoot({
	className,
	variant,
	...props
}: TabsRootProps) {
	const slots = tabsVariants({ variant });

	return (
		<TabsContext value={{ slots }}>
			<Tabs.Root className={slots.root({ className })} {...props} />
		</TabsContext>
	);
}

// packages/svelte/src/lib/components/tabs/tabs-root.svelte
<script lang="ts">
import { cn, type TabsVariants, tabsVariants } from "@adn-ui/core";
import { Tabs as TabsPrimitive } from "bits-ui";
import { setTabsContext } from "./tabs.context.js";

let {
	ref = $bindable(null),
	value = $bindable(),
	class: className,
	variant = "underline",
	...rest
}: TabsPrimitive.RootProps & TabsVariants = $props();

const slots = $derived(tabsVariants({ variant }));
setTabsContext({
	get slots() {
		return slots;
	},
});
</script>

<TabsPrimitive.Root
	bind:ref
	bind:value
	class={cn(slots.root(), className)}
	{...rest}
/>
