// packages/svelte/src/lib/components/dialog/dialog-footer.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getDialogContext } from "./dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

const { slots } = getDialogContext();
</script>

<div
	bind:this={ref}
	class={cn(slots.footer(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>

// packages/react/src/components/dialog/dialog-footer.tsx
import { cn } from "@adn-ui/core";

import { useDialogContext } from "./dialog-context";

export type DialogFooterProps = React.ComponentProps<"div">;

export default function DialogFooter({ className, ...props }: DialogFooterProps) {
  const { slots } = useDialogContext();

  return <div data-slot="dialog-footer" className={cn(slots.footer(), className)} {...props} />;
}
