// packages/svelte/src/lib/components/dialog/dialog-header.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getDialogContext } from "./dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

const { slots } = getDialogContext();
</script>

<div
	bind:this={ref}
	class={cn(slots.header(), className)}
	{...rest}
>
	{@render rest.children?.()}
</div>

// packages/react/src/components/dialog/dialog-header.tsx
import { cn } from "@adn-ui/core";

import { useDialogContext } from "./dialog-context";

export type DialogHeaderProps = React.ComponentProps<"div">;

export default function DialogHeader({ className, ...props }: DialogHeaderProps) {
  const { slots } = useDialogContext();

  return <div data-slot="dialog-header" className={cn(slots.header(), className)} {...props} />;
}
