// packages/svelte/src/lib/components/dialog/dialog-root.svelte
<script lang="ts">
import { dialogVariants } from "@adn-ui/core";
import { Dialog as DialogPrimitive } from "bits-ui";
import { setDialogContext } from "./dialog.context";

let { open = $bindable(false), ...rest }: DialogPrimitive.RootProps = $props();

const slots = dialogVariants();
setDialogContext({ slots });
</script>

<DialogPrimitive.Root bind:open {...rest}>
	{@render rest.children?.()}
</DialogPrimitive.Root>

// packages/react/src/components/dialog/dialog-root.tsx
import { dialogVariants } from "@adn-ui/core";
import { Dialog } from "radix-ui";

import { DialogContext } from "./dialog-context";

export type DialogRootProps = React.ComponentProps<typeof Dialog.Root>;

export default function DialogRoot(props: DialogRootProps) {
	const slots = dialogVariants();

	return (
		<DialogContext value={{ slots }}>
			<Dialog.Root data-slot="dialog-root" {...props} />
		</DialogContext>
	);
}
