// packages/svelte/src/lib/components/dialog/dialog-description.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Dialog as DialogPrimitive } from "bits-ui";
import { getDialogContext } from "./dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DialogPrimitive.DescriptionProps = $props();

const { slots } = getDialogContext();
</script>

<DialogPrimitive.Description
	bind:ref
	class={cn(slots.description(), className)}
	{...rest}
/>

// packages/react/src/components/dialog/dialog-description.tsx
import { cn } from "@adn-ui/core";
import { Dialog } from "radix-ui";

import { useDialogContext } from "./dialog-context";

export type DialogDescriptionProps = React.ComponentProps<typeof Dialog.Description>;

export default function DialogDescription({ className, ...props }: DialogDescriptionProps) {
  const { slots } = useDialogContext();

  return (
    <Dialog.Description
      data-slot="dialog-description"
      className={cn(slots.description(), className)}
      {...props}
    />
  );
}
