// packages/svelte/src/lib/components/dialog/dialog-overlay.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { Dialog as DialogPrimitive } from "bits-ui";
import { getDialogContext } from "./dialog.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DialogPrimitive.OverlayProps = $props();

const { slots } = getDialogContext();
</script>

<DialogPrimitive.Overlay
	bind:ref
	class={cn(slots.overlay(), className)}
	{...rest}
/>

// packages/react/src/components/dialog/dialog-overlay.tsx
import { cn } from "@adn-ui/core";
import { Dialog } from "radix-ui";

import { useDialogContext } from "./dialog-context";

export type DialogOverlayProps = React.ComponentProps<typeof Dialog.Overlay>;

export default function DialogOverlay({ className, ...props }: DialogOverlayProps) {
  const { slots } = useDialogContext();

  return (
    <Dialog.Overlay
      data-slot="dialog-overlay"
      className={cn(slots.overlay(), className)}
      {...props}
    />
  );
}
