// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-separator.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DropdownMenuPrimitive.SeparatorProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.Separator
	bind:ref
	class={cn(slots.separator(), className)}
	{...rest}
/>

// packages/react/src/components/dropdown-menu/dropdown-menu-separator.tsx
import { cn } from "@adn-ui/core";
import { DropdownMenu } from "radix-ui";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuSeparatorProps = React.ComponentProps<typeof DropdownMenu.Separator>;

export default function DropdownMenuSeparator({ className, ...props }: DropdownMenuSeparatorProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.Separator
      data-slot="dropdown-menu-separator"
      className={cn(slots.separator(), className)}
      {...props}
    />
  );
}
