// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-sub-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DropdownMenuPrimitive.SubContentProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.SubContent
	bind:ref
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</DropdownMenuPrimitive.SubContent>

// packages/react/src/components/dropdown-menu/dropdown-menu-sub-content.tsx
import { cn } from "@adn-ui/core";
import { DropdownMenu } from "radix-ui";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuSubContentProps = React.ComponentProps<typeof DropdownMenu.SubContent>;

export default function DropdownMenuSubContent({
  className,
  ...props
}: DropdownMenuSubContentProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.Portal>
      <DropdownMenu.SubContent
        data-slot="dropdown-menu-sub-content"
        className={cn(slots.subContent(), className)}
        {...props}
      />
    </DropdownMenu.Portal>
  );
}
