// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-sub-trigger.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { LucideChevronRight } from "lucide-svelte";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DropdownMenuPrimitive.SubTriggerProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.SubTrigger
	bind:ref
	class={cn(slots.subTrigger(), className)}
	{...rest}
>
	{@render rest.children?.()}
	<LucideChevronRight class="ml-auto size-4" />
</DropdownMenuPrimitive.SubTrigger>

// packages/react/src/components/dropdown-menu/dropdown-menu-sub-trigger.tsx
import { cn } from "@adn-ui/core";
import { ChevronRight } from "lucide-react";
import { DropdownMenu } from "radix-ui";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuSubTriggerProps = React.ComponentProps<typeof DropdownMenu.SubTrigger>;

export default function DropdownMenuSubTrigger({
  children,
  className,
  ...props
}: DropdownMenuSubTriggerProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.SubTrigger
      data-slot="dropdown-menu-sub-trigger"
      className={cn(slots.subTrigger(), className)}
      {...props}
    >
      {children}
      <ChevronRight className="ml-auto size-4" />
    </DropdownMenu.SubTrigger>
  );
}
