// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-label.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DropdownMenuPrimitive.LabelProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.Label
	bind:ref
	class={cn(slots.label(), className)}
	{...rest}
/>

// packages/react/src/components/dropdown-menu/dropdown-menu-label.tsx
import { cn } from "@adn-ui/core";
import { DropdownMenu } from "radix-ui";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuLabelProps = React.ComponentProps<typeof DropdownMenu.Label>;

export default function DropdownMenuLabel({ className, ...props }: DropdownMenuLabelProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.Label
      data-slot="dropdown-menu-label"
      className={cn(slots.label(), className)}
      {...props}
    />
  );
}
