// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	sideOffset = 4,
	...rest
}: DropdownMenuPrimitive.ContentProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.Content
	bind:ref
	{sideOffset}
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</DropdownMenuPrimitive.Content>

// packages/react/src/components/dropdown-menu/dropdown-menu-content.tsx
import { cn } from "@adn-ui/core";
import { DropdownMenu } from "radix-ui";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuContentProps = React.ComponentProps<typeof DropdownMenu.Content>;

export default function DropdownMenuContent({
  children,
  className,
  sideOffset = 4,
  ...props
}: DropdownMenuContentProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.Portal>
      <DropdownMenu.Content
        data-slot="dropdown-menu-content"
        sideOffset={sideOffset}
        className={cn(slots.content(), className)}
        {...props}
      >
        {children}
      </DropdownMenu.Content>
    </DropdownMenu.Portal>
  );
}
