// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-item.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DropdownMenuPrimitive.ItemProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.Item
	bind:ref
	class={cn(slots.item(), className)}
	{...rest}
>
	{@render rest.children?.()}
</DropdownMenuPrimitive.Item>

// packages/react/src/components/dropdown-menu/dropdown-menu-item.tsx
import { cn } from "@adn-ui/core";
import { DropdownMenu } from "radix-ui";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuItemProps = React.ComponentProps<typeof DropdownMenu.Item>;

export default function DropdownMenuItem({ className, ...props }: DropdownMenuItemProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.Item
      data-slot="dropdown-menu-item"
      className={cn(slots.item(), className)}
      {...props}
    />
  );
}
