// packages/react/src/components/dropdown-menu/dropdown-menu-radio-item.tsx
import { cn } from "@adn-ui/core";
import { Circle } from "lucide-react";
import { DropdownMenu } from "radix-ui";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuRadioItemProps = React.ComponentProps<typeof DropdownMenu.RadioItem>;

export default function DropdownMenuRadioItem({
  children,
  className,
  ...props
}: DropdownMenuRadioItemProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.RadioItem
      data-slot="dropdown-menu-radio-item"
      className={cn(slots.radioItem(), className)}
      {...props}
    >
      <DropdownMenu.ItemIndicator className={slots.itemIndicator()}>
        <Circle className="size-2 fill-current" />
      </DropdownMenu.ItemIndicator>
      {children}
    </DropdownMenu.RadioItem>
  );
}

// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-radio-item.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { LucideCircle } from "lucide-svelte";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	value,
	...rest
}: DropdownMenuPrimitive.RadioItemProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.RadioItem
	bind:ref
	{value}
	class={cn(slots.item(), className)}
	{...rest}
>
	{#snippet children({ checked })}
		{#if rest.children}
			{@render rest.children({ checked })}
		{:else}
			{@render rest.children?.()}
			<span class={slots.itemIndicator()}>
				{#if checked}
					<LucideCircle class="size-2 fill-current" />
				{/if}
			</span>
		{/if}
	{/snippet}
</DropdownMenuPrimitive.RadioItem>
