// src/components/ui/dropdown-menu/dropdown-menu-label.tsx
import { DropdownMenu } from "radix-ui";
import { cn } from "tailwind-variants";

import { useDropdownMenuContext } from "./dropdown-menu.context";

export type DropdownMenuLabelProps = React.ComponentProps<typeof DropdownMenu.Label>;

export const DropdownMenuLabel = ({ className, ...props }: DropdownMenuLabelProps) => {
  const { slots } = useDropdownMenuContext();

  return <DropdownMenu.Label className={cn(slots.label(), className)} {...props} />;
};

// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-label.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: DropdownMenuPrimitive.LabelProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.Label
	bind:ref
	class={cn(slots.label(), className)}
	{...rest}
/>
