// packages/react/src/components/dropdown-menu/dropdown-menu-root.tsx
import { dropdownMenuVariants } from "@adn-ui/core";
import { DropdownMenu } from "radix-ui";

import { DropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuRootProps = React.ComponentProps<typeof DropdownMenu.Root>;

export default function DropdownMenuRoot(props: DropdownMenuRootProps) {
  const slots = dropdownMenuVariants();

  return (
    <DropdownMenuContext value={{ slots }}>
      <DropdownMenu.Root data-slot="dropdown-menu-root" {...props} />
    </DropdownMenuContext>
  );
}

// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-root.svelte
<script lang="ts">
import { dropdownMenuVariants } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { setDropdownMenuContext } from "./dropdown-menu.context";

let { open = $bindable(false), ...rest }: DropdownMenuPrimitive.RootProps =
	$props();

const slots = dropdownMenuVariants();
setDropdownMenuContext({ slots });
</script>

<DropdownMenuPrimitive.Root bind:open {...rest}>
	{@render rest.children?.()}
</DropdownMenuPrimitive.Root>
