// packages/react/src/components/dropdown-menu/dropdown-menu-shortcut.tsx
import { cn } from "@adn-ui/core";

import { useDropdownMenuContext } from "./dropdown-menu-context";

export type DropdownMenuShortcutProps = React.ComponentProps<"span">;

export default function DropdownMenuShortcut({ className, ...props }: DropdownMenuShortcutProps) {
  const { slots } = useDropdownMenuContext();

  return (
    <span
      data-slot="dropdown-menu-shortcut"
      className={cn(slots.shortcut(), className)}
      {...props}
    />
  );
}

// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-shortcut.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import type { WithElementRef } from "bits-ui";
import type { HTMLAttributes } from "svelte/elements";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	...rest
}: WithElementRef<HTMLAttributes<HTMLSpanElement>> = $props();

const { slots } = getDropdownMenuContext();
</script>

<span
	bind:this={ref}
	class={cn(slots.shortcut(), className)}
	{...rest}
>
	{@render rest.children?.()}
</span>
