// src/components/ui/dropdown-menu/dropdown-menu-content.tsx
import { DropdownMenu } from "radix-ui";
import { cn } from "tailwind-variants";

import { useDropdownMenuContext } from "./dropdown-menu.context";

export type DropdownMenuContentProps = React.ComponentProps<typeof DropdownMenu.Content>;

export const DropdownMenuContent = ({
  className,
  sideOffset = 4,
  ...props
}: DropdownMenuContentProps) => {
  const { slots } = useDropdownMenuContext();

  return (
    <DropdownMenu.Portal>
      <DropdownMenu.Content
        className={cn(slots.content(), className)}
        sideOffset={sideOffset}
        {...props}
      />
    </DropdownMenu.Portal>
  );
};

// packages/svelte/src/lib/components/dropdown-menu/dropdown-menu-content.svelte
<script lang="ts">
import { cn } from "@adn-ui/core";
import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
import { getDropdownMenuContext } from "./dropdown-menu.context";

let {
	ref = $bindable(null),
	class: className,
	sideOffset = 4,
	...rest
}: DropdownMenuPrimitive.ContentProps = $props();

const { slots } = getDropdownMenuContext();
</script>

<DropdownMenuPrimitive.Content
	bind:ref
	{sideOffset}
	class={cn(slots.content(), className)}
	{...rest}
>
	{@render rest.children?.()}
</DropdownMenuPrimitive.Content>
